# Generated by Django 5.2.6 on 2025-11-29 10:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('amount_limit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('threshold_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('previous_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('change_reason', models.TextField(blank=True)),
                ('change_date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-change_date'],
                'indexes': [models.Index(fields=['-change_date', 'user_id'], name='budget_aler_change__b1a4ad_idx'), models.Index(fields=['user_id', 'category'], name='budget_aler_user_id_6e45ed_idx')],
            },
        ),
    ]
