# Generated by Django 5.2.6 on 2025-11-29 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_alerts', '0002_budgethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetalert',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, help_text='Snooze alerts until this time', null=True),
        ),
        migrations.AddField(
            model_name='budgetalert',
            name='threshold_100',
            field=models.BooleanField(default=True, help_text='Alert at 100% usage'),
        ),
        migrations.AddField(
            model_name='budgetalert',
            name='threshold_50',
            field=models.BooleanField(default=True, help_text='Alert at 50% usage'),
        ),
        migrations.AddField(
            model_name='budgetalert',
            name='threshold_75',
            field=models.BooleanField(default=True, help_text='Alert at 75% usage'),
        ),
        migrations.AddField(
            model_name='budgetalert',
            name='threshold_90',
            field=models.BooleanField(default=True, help_text='Alert at 90% usage'),
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(max_length=64)),
                ('threshold_level', models.PositiveSmallIntegerField(help_text='The threshold percentage that was triggered (50, 75, 90, or 100)')),
                ('severity', models.CharField(choices=[('info', 'Info (50%)'), ('warning', 'Warning (75%)'), ('danger', 'Danger (90%)'), ('critical', 'Critical (100%)')], default='info', max_length=10)),
                ('current_spending', models.DecimalField(decimal_places=2, max_digits=12)),
                ('budget_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('usage_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='budget_alerts.budgetalert')),
            ],
            options={
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['-triggered_at', 'user_id'], name='budget_aler_trigger_dde7a7_idx'), models.Index(fields=['user_id', 'category', 'threshold_level'], name='budget_aler_user_id_5f88c0_idx')],
            },
        ),
    ]
