# Generated by Django 5.2.6 on 2025-11-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('ACCESS_DENIED', 'Access Denied'), ('BUDGET_BREACH', 'Budget Threshold Breach'), ('ALERT_TRIGGERED', 'Alert Triggered')], db_index=True, max_length=20)),
                ('resource_type', models.CharField(choices=[('expense', 'Expense'), ('goal', 'Savings Goal'), ('alert', 'Budget Alert'), ('reminder', 'Reminder'), ('user', 'User'), ('monthly_allowance', 'Monthly Allowance'), ('system', 'System')], db_index=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'user_id'], name='audit_logs__timesta_1b9f17_idx'), models.Index(fields=['action_type', 'resource_type'], name='audit_logs__action__7ece77_idx')],
            },
        ),
    ]
