# Generated by Django 5.2.6 on 2025-10-21 21:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Daily spending limit in Philippine Pesos', max_digits=12),
        ),
    ]
