# Generated by Django 5.2.6 on 2025-10-30 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_add_daily_allowance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, help_text='When the reminder is due', null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='login.user')),
            ],
            options={
                'ordering': ['is_completed', 'due_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_completed'], name='reminders_r_user_id_e58425_idx'), models.Index(fields=['user', 'due_at'], name='reminders_r_user_id_03290d_idx')],
            },
        ),
    ]
