# Generated by Django 5.2.6 on 2025-11-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_budget_alerts', models.BooleanField(default=True)),
                ('email_goal_milestones', models.BooleanField(default=True)),
                ('email_goal_deadlines', models.BooleanField(default=True)),
                ('email_reminders', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=False)),
                ('push_budget_alerts', models.BooleanField(default=True)),
                ('push_goal_milestones', models.BooleanField(default=True)),
                ('push_goal_deadlines', models.BooleanField(default=True)),
                ('push_reminders', models.BooleanField(default=True)),
                ('fcm_token', models.TextField(blank=True, help_text='Firebase Cloud Messaging token', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, help_text='User ID from session')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification'), ('dashboard', 'Dashboard Alert')], max_length=20)),
                ('category', models.CharField(choices=[('budget_alert', 'Budget Alert'), ('goal_milestone', 'Goal Milestone'), ('goal_deadline', 'Goal Deadline'), ('goal_achieved', 'Goal Achieved'), ('reminder', 'Reminder'), ('expense', 'Expense Alert')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='notificatio_user_id_57d53d_idx'), models.Index(fields=['user_id', 'status'], name='notificatio_user_id_d1d348_idx'), models.Index(fields=['notification_type', 'status'], name='notificatio_notific_219496_idx')],
            },
        ),
        migrations.CreateModel(
            name='GoalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_id', models.BigIntegerField(db_index=True)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('alert_type', models.CharField(choices=[('milestone_25', '25% Progress'), ('milestone_50', '50% Progress'), ('milestone_75', '75% Progress'), ('milestone_100', 'Goal Achieved'), ('deadline_week', '1 Week to Deadline'), ('deadline_day', '1 Day to Deadline'), ('deadline_passed', 'Deadline Passed')], max_length=30)),
                ('triggered', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_logs', models.ManyToManyField(blank=True, related_name='goal_alerts', to='notifications.notificationlog')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['goal_id', 'triggered'], name='notificatio_goal_id_2c0cb0_idx'), models.Index(fields=['user_id', '-created_at'], name='notificatio_user_id_4d0d64_idx')],
                'unique_together': {('goal_id', 'alert_type')},
            },
        ),
    ]
